Random small UI changes
koerismo/PBR-2-Source pull request #6
Opened 2024-07-13 22:40 UTC by JJL772

* Added tooltip to the image icons that displays file name and how to remove the file
* Added stretch to left side layout to prevent excessive vertical spacing between the elements if the UI is resized
* Configure minimum size based on the `sizeHint` after all elements have been added to the layout

2024-07-13 23:45 UTC, koerismo requested changes

2024-07-13 23:45 UTC, koerismo commented on src/module/gui/__init__.py
> +			self.iconButton.setToolTip(f'{os.path.basename(self.path)}  Right-click to remove')
Since this is already a Path, we can just use `self.path.name` instead of `os.path.basename(self.path)`

2024-07-13 23:45 UTC, koerismo commented on src/module/gui/__init__.py
> +import os
See comment 2

2024-07-13 23:57 UTC, koerismo requested changes

2024-07-13 23:57 UTC, koerismo commented on src/module/gui/__init__.py
> +			self.iconButton.setToolTip('')
(whoops, forgot to say this in round 1) This should actually probably all be in `self.reload`. `set_icon` is only called after the image is loaded in, so if the image fails to load then users will never get the 'right click to remove' hint.

```py
def reload(self):
	self.iconButton.setToolTip(f'{self.path.name} Right-click to remove' if self.path else '')
	self.path_box.setText(self.path.name if self.path else '')
	self.picked.emit(self.kind, self.path, self.set_icon)
	self.update_required()
```

2024-07-16 19:18 UTC, koerismo approved these changes

2024-07-16 19:18 UTC, merged

2024-07-16 20:35 UTC, JJL772 commented
Thanks for addressing this for me!